name: apache-superset-a2i-beautiful_rubin
services:
  db:
    container_name: superset_db
    environment:
      COMPOSE_PROJECT_NAME: superset
      CYPRESS_CONFIG: "false"
      DATABASE_DB: superset
      DATABASE_DIALECT: postgresql
      DATABASE_HOST: db
      DATABASE_PASSWORD: superset
      DATABASE_PORT: "5432"
      DATABASE_USER: superset
      FLASK_ENV: development
      MYSQL_DATABASE: superset
      MYSQL_PASSWORD: superset
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: superset
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      SUPERSET_ENV: development
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_PORT: "8088"
    env_file:
    - docker/.env
    image: postgres:14
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: apache-superset-a2i-beautiful_rubin
    networks:
      default: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 5432
      published: "5432"
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: volume
      source: db_home
      target: /var/lib/postgresql/data
      volume: {}
  mysql:
    container_name: mysql_db
    environment:
      COMPOSE_PROJECT_NAME: superset
      CYPRESS_CONFIG: "false"
      DATABASE_DB: superset
      DATABASE_DIALECT: postgresql
      DATABASE_HOST: db
      DATABASE_PASSWORD: superset
      DATABASE_PORT: "5432"
      DATABASE_USER: superset
      FLASK_ENV: development
      MYSQL_DATABASE: superset
      MYSQL_PASSWORD: superset
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: superset
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      SUPERSET_ENV: development
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_PORT: "8088"
    env_file:
    - docker/.env
    image: mysql:latest
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: apache-superset-a2i-beautiful_rubin
    networks:
      default: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 3306
      published: "33060"
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\docker
      target: /app/docker
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset
      target: /app/superset
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset-frontend
      target: /app/superset-frontend
      bind:
        create_host_path: true
    - type: volume
      source: superset_home
      target: /app/superset_home
      volume: {}
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\tests
      target: /app/tests
      bind:
        create_host_path: true
  redis:
    container_name: superset_cache
    image: redis:latest
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: apache-superset-a2i-beautiful_rubin
    networks:
      default: null
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 6379
      published: "6379"
      protocol: tcp
    restart: unless-stopped
    volumes:
    - type: volume
      source: redis
      target: /data
      volume: {}
  superset:
    command:
    - /app/docker/docker-bootstrap.sh
    - app
    container_name: superset_app
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      COMPOSE_PROJECT_NAME: superset
      CYPRESS_CONFIG: ""
      DATABASE_DB: superset
      DATABASE_DIALECT: postgresql
      DATABASE_HOST: db
      DATABASE_PASSWORD: superset
      DATABASE_PORT: "5432"
      DATABASE_USER: superset
      FLASK_ENV: development
      MYSQL_DATABASE: superset
      MYSQL_PASSWORD: superset
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: superset
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      SUPERSET_ENV: development
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_PORT: "8088"
    env_file:
    - docker/.env
    image: apache/superset:latest-dev
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: apache-superset-a2i-beautiful_rubin
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8088
      published: "8088"
      protocol: tcp
    restart: unless-stopped
    user: root
    volumes:
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\docker
      target: /app/docker
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset
      target: /app/superset
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset-frontend
      target: /app/superset-frontend
      bind:
        create_host_path: true
    - type: volume
      source: superset_home
      target: /app/superset_home
      volume: {}
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\tests
      target: /app/tests
      bind:
        create_host_path: true
  superset-init:
    command:
    - /app/docker/docker-init.sh
    container_name: superset_init
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      COMPOSE_PROJECT_NAME: superset
      CYPRESS_CONFIG: ""
      DATABASE_DB: superset
      DATABASE_DIALECT: postgresql
      DATABASE_HOST: db
      DATABASE_PASSWORD: superset
      DATABASE_PORT: "5432"
      DATABASE_USER: superset
      FLASK_ENV: development
      MYSQL_DATABASE: superset
      MYSQL_PASSWORD: superset
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: superset
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      SUPERSET_ENV: development
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_PORT: "8088"
    env_file:
    - docker/.env
    image: apache/superset:latest-dev
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: apache-superset-a2i-beautiful_rubin
    networks:
      default: null
    user: root
    volumes:
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\docker
      target: /app/docker
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset
      target: /app/superset
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset-frontend
      target: /app/superset-frontend
      bind:
        create_host_path: true
    - type: volume
      source: superset_home
      target: /app/superset_home
      volume: {}
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\tests
      target: /app/tests
      bind:
        create_host_path: true
  superset-node:
    command:
    - /app/docker/docker-frontend.sh
    container_name: superset_node
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      COMPOSE_PROJECT_NAME: superset
      CYPRESS_CONFIG: "false"
      DATABASE_DB: superset
      DATABASE_DIALECT: postgresql
      DATABASE_HOST: db
      DATABASE_PASSWORD: superset
      DATABASE_PORT: "5432"
      DATABASE_USER: superset
      FLASK_ENV: development
      MYSQL_DATABASE: superset
      MYSQL_PASSWORD: superset
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: superset
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      SUPERSET_ENV: development
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_PORT: "8088"
    env_file:
    - docker/.env
    image: node:16
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: apache-superset-a2i-beautiful_rubin
    networks:
      default: null
    volumes:
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\docker
      target: /app/docker
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset
      target: /app/superset
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset-frontend
      target: /app/superset-frontend
      bind:
        create_host_path: true
    - type: volume
      source: superset_home
      target: /app/superset_home
      volume: {}
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\tests
      target: /app/tests
      bind:
        create_host_path: true
  superset-tests-worker:
    command:
    - /app/docker/docker-bootstrap.sh
    - worker
    container_name: superset_tests_worker
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      COMPOSE_PROJECT_NAME: superset
      CYPRESS_CONFIG: "false"
      DATABASE_DB: test
      DATABASE_DIALECT: postgresql
      DATABASE_HOST: localhost
      DATABASE_PASSWORD: superset
      DATABASE_PORT: "5432"
      DATABASE_USER: superset
      FLASK_ENV: development
      MYSQL_DATABASE: superset
      MYSQL_PASSWORD: superset
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: superset
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_CELERY_DB: "2"
      REDIS_HOST: localhost
      REDIS_PORT: "6379"
      REDIS_RESULTS_DB: "3"
      SUPERSET_ENV: development
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_PORT: "8088"
    env_file:
    - docker/.env
    image: apache/superset:latest-dev
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: apache-superset-a2i-beautiful_rubin
    network_mode: host
    user: root
    volumes:
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\docker
      target: /app/docker
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset
      target: /app/superset
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset-frontend
      target: /app/superset-frontend
      bind:
        create_host_path: true
    - type: volume
      source: superset_home
      target: /app/superset_home
      volume: {}
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\tests
      target: /app/tests
      bind:
        create_host_path: true
  superset-websocket:
    build:
      context: E:\server_python\Superset\apache-superset-a2i\superset-websocket
      dockerfile: Dockerfile
    container_name: superset_websocket
    depends_on:
      redis:
        condition: service_started
    environment:
      PORT: "8080"
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      REDIS_SSL: "false"
    image: superset-websocket
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.compose.build: "true"
      com.docker.devenvironments.name: apache-superset-a2i-beautiful_rubin
    networks:
      default: null
    ports:
    - mode: ingress
      target: 8080
      published: "8080"
      protocol: tcp
    volumes:
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset-websocket
      target: /home/superset-websocket
      bind:
        create_host_path: true
    - type: volume
      target: /home/superset-websocket/node_modules
      volume: {}
    - type: volume
      target: /home/superset-websocket/dist
      volume: {}
  superset-worker:
    command:
    - /app/docker/docker-bootstrap.sh
    - worker
    container_name: superset_worker
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      COMPOSE_PROJECT_NAME: superset
      CYPRESS_CONFIG: "false"
      DATABASE_DB: superset
      DATABASE_DIALECT: postgresql
      DATABASE_HOST: db
      DATABASE_PASSWORD: superset
      DATABASE_PORT: "5432"
      DATABASE_USER: superset
      FLASK_ENV: development
      MYSQL_DATABASE: superset
      MYSQL_PASSWORD: superset
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: superset
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      SUPERSET_ENV: development
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_PORT: "8088"
    env_file:
    - docker/.env
    image: apache/superset:latest-dev
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: apache-superset-a2i-beautiful_rubin
    networks:
      default: null
    restart: unless-stopped
    user: root
    volumes:
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\docker
      target: /app/docker
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset
      target: /app/superset
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset-frontend
      target: /app/superset-frontend
      bind:
        create_host_path: true
    - type: volume
      source: superset_home
      target: /app/superset_home
      volume: {}
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\tests
      target: /app/tests
      bind:
        create_host_path: true
  superset-worker-beat:
    command:
    - /app/docker/docker-bootstrap.sh
    - beat
    container_name: superset_worker_beat
    depends_on:
      db:
        condition: service_started
      redis:
        condition: service_started
    environment:
      COMPOSE_PROJECT_NAME: superset
      CYPRESS_CONFIG: "false"
      DATABASE_DB: superset
      DATABASE_DIALECT: postgresql
      DATABASE_HOST: db
      DATABASE_PASSWORD: superset
      DATABASE_PORT: "5432"
      DATABASE_USER: superset
      FLASK_ENV: development
      MYSQL_DATABASE: superset
      MYSQL_PASSWORD: superset
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_USER: superset
      POSTGRES_DB: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: superset
      PYTHONPATH: /app/pythonpath:/app/docker/pythonpath_dev
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      SUPERSET_ENV: development
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_PORT: "8088"
    env_file:
    - docker/.env
    image: apache/superset:latest-dev
    labels:
      com.docker.devenvironments.compose: "true"
      com.docker.devenvironments.name: apache-superset-a2i-beautiful_rubin
    networks:
      default: null
    restart: unless-stopped
    user: root
    volumes:
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\docker
      target: /app/docker
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset
      target: /app/superset
      bind:
        create_host_path: true
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\superset-frontend
      target: /app/superset-frontend
      bind:
        create_host_path: true
    - type: volume
      source: superset_home
      target: /app/superset_home
      volume: {}
    - type: bind
      source: E:\server_python\Superset\apache-superset-a2i\tests
      target: /app/tests
      bind:
        create_host_path: true
networks:
  default:
    name: apache-superset-a2i-beautiful_rubin_default
volumes:
  db_home:
    name: apache-superset-a2i-beautiful_rubin_db_home
  db_mysql:
    name: apache-superset-a2i-beautiful_rubin_db_mysql
  redis:
    name: apache-superset-a2i-beautiful_rubin_redis
  superset_home:
    name: apache-superset-a2i-beautiful_rubin_superset_home
x-superset-depends-on:
- db
- redis
x-superset-image: apache/superset:latest-dev
x-superset-user: root
x-superset-volumes:
- ./docker:/app/docker
- ./superset:/app/superset
- ./superset-frontend:/app/superset-frontend
- superset_home:/app/superset_home
- ./tests:/app/tests
